# message = ("hello guys are u there!")
# print(message.title())

# message = ("hello baby are u there!")
# print(message)
# student = ("gamvir is a good student.")
# s_capitalize = student.capitalize()
# print(s_capitalize.center(45))
# name = ("Gamvir Darlami")
# print(name.lower())
# name = ("jamuna thapa")
# print(name.upper())
# name = ("Hello Mom")
# print(name.casefold())
full_name = ("rammaya darlami")
print("Hello, " + full_name.title() + "!")